// Generated by CoffeeScript 1.4.0
(function() {
  var app, express, moment, util;

  express = require("express");

  app = express();

  util = require("util");

  moment = require('moment');

  module.exports = function(config) {
    app.set("view options", {
      doctype: "html"
    });
    app.set("view engine", "jade");
    app.set("views", __dirname + "/views");
    app.use(express.favicon());
    app.use(express["static"](__dirname + "/public"));
    app.get("/service/list", function(req, res) {
      return res.json(serviceList);
    });
    app.get(config.startPath, function(req, res) {
      return res.render('dashboard', {
        services: serviceList
      });
    });
    app.get("/service/:name/status", function(req, res) {
      var info, name;
      name = decodeURI(req.param('name'));
      if (!(serviceList[name] != null)) {
        return res.send('Not Found Service', 400);
      }
      info = serviceList[name].info;
      return res.json(info);
    });
    app.get('/timezone', function(req, res) {
      return res.json({
        datetime: moment().format('LLL'),
        offset: (moment().zone() / 60) * -1
      });
    });
    return app;
  };

}).call(this);
