// Generated by CoffeeScript 1.4.0
(function() {
  var EventEmitter, Updown, config, cronJob, exports, mailOptions, mailer, moment, nodemailer, request, timeFormat, util;

  request = require('request');

  global.serviceList = {};

  util = require('util');

  moment = require('moment');

  cronJob = require('cron').CronJob;

  timeFormat = 'MMM D YYYY, h:mm:ss a';

  nodemailer = require("nodemailer");

  mailer = {};

  mailOptions = {};

  config = {
    startPath: '/dashboard'
  };

  Updown = function(name, config) {
    this.name = name;
    this.config = config;
    this.config.cronTime = this.config.cronTime || '00 */1 * * * *';
    this.service_name = name.toLowerCase();
    if (serviceList[this.service_name] != null) {
      throw new Error("Duplicate service name: " + this.name);
    }
    if (this.config.ping != null) {
      this.init();
    }
    return this;
  };

  EventEmitter = require("events").EventEmitter;

  exports = module.exports = Updown;

  exports.version = "0.0.1";

  exports.createService = function(name, config) {
    return new Updown(name, config);
  };

  exports.setPath = function(path) {
    return config.startPath = path;
  };

  exports.middleware = function() {
    var app;
    app = require("./http")(config);
    return app;
  };

  /*
  Inherit from `EventEmitter.prototype`.
  */


  Updown.prototype.__proto__ = EventEmitter.prototype;

  Updown.prototype.init = function() {
    var self;
    self = this;
    this.on('error', function() {});
    serviceList[this.service_name] = this.config;
    this.setCronTime('ping');
    serviceList[this.service_name].info = {};
    serviceList[this.service_name].name = this.name.replace(/\s/g, '-');
    serviceList[this.service_name].name_origin = this.name;
    serviceList[this.service_name].info.interval = this.cronTime.cronTime.getTimeout();
    if ((this.config.ping != null) && this.config.ping === true) {
      return this.ping(this);
    }
  };

  Updown.prototype.ping = function() {
    var interval, self, url;
    self = this;
    url = this.config.url;
    interval = this.cronTime._timeout._idleTimeout / 1000;
    serviceList[this.service_name].info.last_run = moment().format(timeFormat);
    serviceList[this.service_name].info.next_run = moment().add('seconds', interval).format(timeFormat);
    return request(url, function(err, res, body) {
      if (err != null) {
        self.isNotOk();
        return self.emit('error', err);
      } else {
        if (res.statusCode === 200) {
          self.isOk();
          return self.emit('success', res, body);
        } else {
          return self.emit('error', body);
        }
      }
    });
  };

  Updown.prototype.process = function(fn) {
    var done, interval, self;
    self = this;
    this.init();
    this.process_fn = fn;
    this.setCronTime('process');
    interval = this.cronTime._timeout._idleTimeout / 1000;
    serviceList[this.service_name].info.last_run = moment().format(timeFormat);
    serviceList[this.service_name].info.next_run = moment().add('seconds', interval).format(timeFormat);
    done = {
      success: function(data) {
        return self.success(data);
      },
      error: function(data) {
        return self.error(data);
      }
    };
    return fn(done);
  };

  Updown.prototype.setCronTime = function(type) {
    var self;
    self = this;
    try {
      return this.cronTime = new cronJob({
        cronTime: self.config.cronTime,
        onTick: function() {
          if (type === 'ping') {
            return self.ping();
          } else if (type === 'process') {
            return self.process(self.process_fn);
          } else {
            return thorw(new Error('setCrontime type not valid'));
          }
        },
        start: true
      });
    } catch (e) {
      throw new Error('Cron pattern not valid');
    }
  };

  Updown.prototype.error = function(data) {
    return this.isNotOk(data);
  };

  Updown.prototype.success = function(data) {
    return this.isOk(data);
  };

  Updown.prototype.isOk = function(data) {
    if (data == null) {
      data = null;
    }
    serviceList[this.service_name].info.data = data;
    this.state = 'UP';
    serviceList[this.service_name].info.status = 'UP';
    return serviceList[this.service_name].info.interval = this.cronTime.cronTime.getTimeout();
  };

  Updown.prototype.isNotOk = function(data) {
    if (data == null) {
      data = null;
    }
    if (this.state === 'UP' && this.config.sendmail === true) {
      this.sendMail();
    }
    serviceList[this.service_name].info.data = data;
    this.state = 'DOWN';
    serviceList[this.service_name].info.status = 'DOWN';
    return serviceList[this.service_name].info.interval = this.cronTime.cronTime.getTimeout();
  };

  Updown.prototype.sendMail = function() {
    var self;
    self = this;
    mailOptions.subject = "Service [ " + this.name + " ] is down";
    mailOptions.html = "<b>Location</b> : " + this.config.url + " <br>\n<b>Check Time</b> : " + (moment().format('LLL'));
    mailer.sendMail(mailOptions, function(error, response) {
      if (error) {
        console.log('Send email error');
        return console.log(error);
      } else {
        return console.log("Email sent: " + self.name + " ");
      }
    });
    return mailer.close();
  };

  exports.mailConfig = function(config) {
    mailer = nodemailer.createTransport("SMTP", {
      service: config.service,
      auth: {
        user: "bot@jitta.com",
        pass: "1r2o3b4o5t"
      }
    });
    return mailOptions = {
      to: config.to
    };
  };

}).call(this);
